name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "deploy/cert-manager-webhook-glesys/Chart.yaml"
  workflow_dispatch:

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Set up yq (for reading Chart.yaml)
        uses: mikefarah/yq@v4.45.4

      - name: Read version from Chart.yaml
        id: chart_info
        run: |
          CHART_DIR="deploy/cert-manager-webhook-glesys"
          CHART_VERSION=$(yq '.version' "${CHART_DIR}/Chart.yaml")
          APP_VERSION=$(yq '.appVersion' "${CHART_DIR}/Chart.yaml")
          CHART_NAME=$(yq '.name' "${CHART_DIR}/Chart.yaml")
          echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "chart_name=$CHART_NAME" >> $GITHUB_OUTPUT
          echo "Releasing Chart: $CHART_NAME, Version: $CHART_VERSION, AppVersion: $APP_VERSION"

      - name: Helm Lint
        run: helm lint ./deploy/cert-manager-webhook-glesys

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Package
        id: helm_package
        run: |
          CHART_DIR="./deploy/cert-manager-webhook-glesys"
          helm dependency update "$CHART_DIR"
          helm package "$CHART_DIR"
          PACKAGE_NAME="${{ steps.chart_info.outputs.chart_name }}-${{ steps.chart_info.outputs.chart_version }}.tgz"
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "Packaged chart: $PACKAGE_NAME"

      - name: Helm Push
        env:
          CHART_PACKAGE: /charts/${{ steps.helm_package.outputs.package_name }}
          OCI_REGISTRY: ghcr.io/${{ github.repository_owner }}
          CHART_NAME: ${{ steps.chart_info.outputs.chart_name }}
        run: |
          echo "Pushing $CHART_PACKAGE to $OCI_REGISTRY/$CHART_NAME"
          helm push "$CHART_PACKAGE" "oci://$OCI_REGISTRY"
