name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
      - "dev-*"
  pull_request:
    branches:
      - main

jobs:
  build_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine if image publish event
        id: publish_check
        run: |
          IS_PUBLISH_EVENT="false"
          if [[ "${{ github.event_name }}" == "push" && \
                ( "${{ github.ref }}" == refs/tags/v* || "${{ github.ref }}" == refs/tags/dev-* ) ]]; then
            IS_PUBLISH_EVENT="true"
          fi
          echo "is_publish_event=${IS_PUBLISH_EVENT}" >> $GITHUB_OUTPUT

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: steps.publish_check.outputs.is_publish_event == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # For v*.*.* tags (semver)
            type=semver,pattern=v{{version}},enable=${{startsWith(github.ref, 'refs/tags/v')}}
            type=semver,pattern=v{{major}}.{{minor}},enable=${{startsWith(github.ref, 'refs/tags/v')}}
            type=semver,pattern=v{{major}},enable=${{startsWith(github.ref, 'refs/tags/v')}}

            # For dev-* tags (use the tag name as is)
            type=ref,event=tag,enable=${{startsWith(github.ref, 'refs/tags/dev-')}}

            # For all pushes/PRs
            type=sha
            type=ref,event=pr
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ steps.publish_check.outputs.is_publish_event == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release_chart:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    needs: build_image
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine if chart publish event
        id: publish_check
        run: |
          IS_PUBLISH_EVENT="false"
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/v* ]]; then
            IS_PUBLISH_EVENT="true"
          fi
          echo "is_publish_event=${IS_PUBLISH_EVENT}" >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Helm Lint
        run: helm lint ./deploy/cert-manager-webhook-glesys

      - name: Set up yq (for reading Chart.yaml)
        if: steps.publish_check.outputs.is_publish_event == 'true'
        uses: mikefarah/yq@v4.45.4

      - name: Read and verify Chart.yaml
        if: steps.publish_check.outputs.is_publish_event == 'true'
        id: chart_info
        run: |
          CHART_DIR="deploy/cert-manager-webhook-glesys"
          CHART_FILE_VERSION=$(yq '.version' "${CHART_DIR}/Chart.yaml")
          CHART_NAME=$(yq '.name' "${CHART_DIR}/Chart.yaml")
          APP_VERSION=$(yq '.appVersion' "${CHART_DIR}/Chart.yaml") # Read the manually set appVersion

          GIT_TAG="${{ github.ref }}"
          TAG_VERSION_FROM_GIT=${GIT_TAG#refs/tags/v}

          echo "Performing Git tag vs Chart.yaml version check..."
          echo "Git tag: $GIT_TAG"
          echo "Extracted tag version: $TAG_VERSION_FROM_GIT"
          echo "Chart.yaml version: $CHART_FILE_VERSION"
          echo "Chart.yaml appVersion: $APP_VERSION"

          if [[ "$TAG_VERSION_FROM_GIT" != "$CHART_FILE_VERSION" ]]; then
            echo "Error: Git tag version ($TAG_VERSION_FROM_GIT) does not match Chart.yaml version ($CHART_FILE_VERSION)."
            exit 1
          fi

          if [[ "$TAG_VERSION_FROM_GIT" != "$APP_VERSION" ]]; then
            echo "Error: Git tag version ($TAG_VERSION_FROM_GIT) does not match Chart.yaml appVersion ($APP_VERSION)."
            exit 1
          fi

          echo "chart_version=$CHART_FILE_VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "chart_name=$CHART_NAME" >> $GITHUB_OUTPUT
          echo "Releasing Chart: $CHART_NAME, Version: $CHART_FILE_VERSION, AppVersion: $APP_VERSION"

      - name: Log in to GitHub Container Registry
        if: steps.publish_check.outputs.is_publish_event == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Package
        if: steps.publish_check.outputs.is_publish_event == 'true'
        id: helm_package
        run: |
          CHART_DIR="./deploy/cert-manager-webhook-glesys"
          helm dependency update "$CHART_DIR"
          helm package "$CHART_DIR"
          PACKAGE_NAME="${{ steps.chart_info.outputs.chart_name }}-${{ steps.chart_info.outputs.chart_version }}.tgz"
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "Packaged chart: $PACKAGE_NAME"

      - name: Helm Push
        if: steps.publish_check.outputs.is_publish_event == 'true'
        env:
          CHART_PACKAGE: ${{ steps.helm_package.outputs.package_name }}
          OCI_REGISTRY: ghcr.io/${{ github.repository_owner }}/charts
          CHART_NAME: ${{ steps.chart_info.outputs.chart_name }}
        run: |
          echo "Pushing $CHART_PACKAGE to $OCI_REGISTRY/$CHART_NAME"
          helm push "$CHART_PACKAGE" "oci://$OCI_REGISTRY"
